# Site settings
title: A non-technical guide to understanding the web
email: kakyou_tensai@yahoo.com
description: An introduction to the web and how it works for the non-programmer.
baseurl: /web-for-non-techies

permalink: /:title/

github_username: huijing
twitter_username: hj_chen

# Build settings
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Exclude files and folder
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - README.md
  - Gemfile
  - Gemfile.lock

# Site defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
